name: Incremental SQL Deployment

run-name: Setting up the Hawthorn database
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: Test Output
      run: echo "Here is a test"
  connect-db:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install the SQL client (e.g., MySQL or PostgreSQL)
      run: |
          sudo apt-get install mysql-client
          
    - name: Show databases
      run: mysql -h localhost --port 3306 -u root -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES";
