name: Incremental SQL Deployment

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with the desired Python version

      - name: Install dependencies
        run: pip install mysql-connector-python # Install necessary Python libraries

      - name: Deploy SQL Scripts
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST_2: ${{ secrets.DB_HOST_2 }}
          DB_PORT_2: ${{ secrets.DB_PORT_2 }}
          DB_NAME_2: ${{ secrets.DB_NAME_2 }}
          DB_USER_2: ${{ secrets.DB_USER_2 }}
          DB_PASSWORD_2: ${{ secrets.DB_PASSWORD_2 }}
        run: python sqldbdeploy.py
