name: Incremental SQL Deployment test4

on:
  push:
    branches:
      - test4  # Replace with your branch name

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
           fetch-depth: 5

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with the desired Python version

      - name: Install dependencies
        run: pip install mysql-connector-python GitPython # Install necessary Python libraries

      - name: Deploy SQL Scripts
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python sqldbdeploy.py
